config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get 'pages/home', to: 'pages#home'
  get 'pages/about', to: 'pages#about'

  resources :articles #CRUD paths

  get 'signup', to: 'users#new'
  # post 'users', to: 'users#create'
#   Otra forma de hacelro es usando
  resources :users, except: [:new]

  get 'login', to: 'session#new'
  post 'login', to: 'session#create'
  delete 'logout', to: 'session#destroy'

  resources :categories, except: [:destroy]

end

app/models/article.rb
class Article <  ActiveRecord::Base
  belongs_to :user
  validates :title, presence: true, length: {minimum: 3, maximum: 50}
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  validates :user_id, presence: true 

end

app/models/user.rb
class User < ActiveRecord::Base
  # Hace que el username se arequerido
  validates :username, presence: true, length: { minimum: 3, maximum: 25 },
            # Para hacerlo sensitivo esto uniqueness: true se cambia por
            # Esto ignora el la sensibilidad de caracteres.
            uniqueness: { case_sensitive: false }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true, length:  {maximum: 105 },
            uniqueness: { case_sensitive: false },
            # Esta forma me valida el formato del correo
            # Suando VALID_EMAIL_REGEX y esto se hace usando regular expresions
            format: { with: VALID_EMAIL_REGEX }



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/articles_controller.rb
class ArticlesController <  ApplicationController
  before_action :set_article, only: [:edit,:update,:show,:destroy]

  def index
    # @articles = Article.all
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def show
    # @article = Article.find(params[:id])
  end

  def destroy
    # @article = Article.find(params[:id])
    @article.destroy
    flash[:danger] = "Articel was successfully deleted"
    redirect_to articles_path
  end

  def new
    @article = Article.new
  end

  def edit
    # Debe existir el id si no no podemos vizualizarlo
    # @article = Article.find(params[:id])
  end

  def update
    # @article = Article.find(params[:id])

    if @article.update(article_params)
      flash[:success] = "Article was successfully updated"
      redirect_to article_path(@article)
    else
      render "edit"
    end
  end

  def create
    # debugger #esto genera un debug en la consola, y se detiene usando ctrl + d y avanza pul
    # render plain: params[:article].inspect
    @article = Article.new(article_params)
    # @article.save
    # redirect_to article_path(@article)
    # @article.user = User.first #hard way
    # @article.user = current_user #esto es por que se esta requiriendo el suaurio en beforeaction required_user

    if @article.save
      #do something
      flash[:success] = "The article was successfully created"
      redirect_to article_path(@article)
    else
      render "new"
    end
  end

  private
  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end



end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_user?
  end
  def about

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "http://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url,alt: user.username, class: "img-circle")
  end
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
    <div class="row">
      <div class="col-xs-8 col-xs-offset-2">
        <div class="well well -lg">
          <div class="article-title">
            <%= link_to article.title, article_path(article) %>
          </div>
          <div class="article-body">
            <%= truncate(article.description, length: 100) %>
            <div class="article-meta-details">
              <small>Creaeted by: <strong><%= article.user.username if article.user %></strong>,
                <%= time_ago_in_words(article.created_at)%> ago
                last updated: <%= time_ago_in_words(article.updated_at) %> ago
              </small>
            </div>
          </div>
          <% if logged_user? && (current_user == article.user || current_user.admin?) %>
          <div class="article-actions">
            <%= link_to "Edit this article",edit_article_path(article), class:"btn btn-xs btn-primary" %>
            <%= link_to "Delete this article", article_path(article),
                        method: :delete,
                        data: { confirm: "Are you sure you want to delete the article? "},
                        class: "btn btn-xs btn-danger" %>

          </div>
              <% end %>
        </div>
      </div>
    </div>
<% end %>

app/views/articles/_form.html.erb
<%= render "shared/errors", obj: @article %>
<div class="row">
  <div class="col-xs-12">
    <%= form_for(@article, :html=> { class:"form-horizontal", role: "form" }) do |f| %>
        <div class="form-group">
          <div class="control-label col-sm-2">
            <%= f.label :title %>
          </div>
          <div class="col-sm-8">
            <%= f.text_field :title, class:"form-control", placeholder:"Title of Article", autofocus:true %>
          </div>
        </div>
        <div class="form-group">
          <div class="control-label col-sm-2">
            <%= f.label :description %>
          </div>
          <div class="col-md-8">
            <%= f.text_area :description, rows: 10, class:"form-control", placeholder:"Body of Article" %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <%= f.submit class: 'btn btn-primary btn-lg' %>
          </div>
        </div>
    <% end %>
    <div class="col-xs-4 col-xs-offset-4">
      [ <%= link_to "Cancel request and return to articles listing",articles_path %> ]
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 align="center">Edit existing article</h1>

<%= render "form" %>

app/views/articles/index.html.erb
<h1 align="center">Listing of articles</h1>
 <div align="center">
   <%= will_paginate %>
 </div>
<%= render "article", obj: @articles %>
<div align="center">
  <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<h1 align="center">Create and article</h1>

<%= render "form" %>

app/views/articles/show.html.erb
<h2 align="center"><%= @article.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">
  <h4 class="center description">
    <strong>Description:</strong>
  </h4>
  <hr>
  <% if @article.user %>
    <ul class="listing">
      <div class="row">
        <div class="well col-md-4 col-md-offset-4">
            <li>Create By:</li>
            <li>
              <%= link_to(gravatar_for(@article.user), user_path(@article.user)) if @article.user %>
            </li>
            <li class="article-title">
              <%= link_to(@article.user.username, users_path(@article.user)) if @article.user %>
            </li>
            <li>
              <small><%= pluralize(@article.user.articles.count,"articles") if @article.user.articles %></small>
            </li>
        </div>
      </div>
    </ul>
  <% end %>
  <%= simple_format(@article.description) %>
    <div class="article-actions">
      <% if logged_user? && (current_user == @article.user || current_user.admin?) %>
        <%= link_to "Edit this article",edit_article_path(@article), class:"btn btn-xs btn-primary" %>
        <%= link_to "Delete this article", article_path(@article),
                    method: :delete,
                    data: { confirm: "Are you sure you want to delete the article? "},
                    class: "btn btn-xs btn-danger" %>

      <% end %>
      <%= link_to "View all artccles",articles_path, class: "btn btn-xs btn-success" %>
    </div>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>
      Copyright &copy; <a href="https://www.udemy.com">The Complete Ruby on Rails Developers</a> By <a href="http://www.awesomemedia.do">Awesome Media</a>
    </small>
    <nav>
      <ul>
        <li>
          <%= link_to "About", pages_about_path %>
        </li>
      </ul>
    </nav>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
  <% flash.each do |name,msg| %>
        <div class='alert alert-<%= "#{name}"%>'>
          <a href="#" class="close" data-dismiss="alert">&#215;</a>
          <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
        </div>
  <% end %>
</div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Alpha Blog",root_path, class: "navbar-brand", id:"logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Articles",articles_path %></li>
        <li><%= link_to "Users", users_path %></li>
        <% if logged_user? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "New Article",new_article_path %></li>
            <li><a href=" ">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
            <% end %>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_user? %>
          <li>
            <%= link_to 'Log out', logout_path, method: :delete, data: {confirm: "You want to get logout ?"}%>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your profile <%= "Admin" if current_user.admin? %><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit your profile", edit_user_path(current_user) %></li>
              <li><%= link_to "View your profile", user_path(current_user) %></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li>
        <% else %>
            <li>
              <%= link_to 'Log in', login_path %>
            </li>
            <li>
              <%= link_to 'Sign up', signup_path %>
            </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlphaBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "layouts/navigation" %>
<%= render "layouts/messages" %>
<div class="container">
  <%= yield %>
</div>
<%= render "layouts/footer" %>
<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/pages/about.html.erb
<h2>Esta es la pagina que me gusta. </h2>

app/views/pages/home.html.erb
<div class="center jumbotron">
<h1>ALPHA BLOG</h1>
<%= link_to "Sign Up Now",signup_path ,class: "btn btn-danger btn-xlarge" %>
</div>

app/views/session/new.html.erb
<h1 align="center">
  Login
</h1>

<%= form_for(:session, :html=> { class:"form-horizontal", role: "form" }, url: login_path) do |f| %>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :email %>
      </div>
      <div class="col-sm-8">
        <%= f.email_field :email, class:"form-control", placeholder:"Enter email", autofocus:true %>
      </div>
    </div>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :password %>
      </div>
      <div class="col-sm-8">
        <%= f.password_field :password, class: "form-control", autocomplete: "off" %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit "Log in" , class: 'btn btn-primary btn-lg' %>
      </div>
    </div>
<% end %>
<div class="col-xs-4 col-xs-offset-4">
  [ <%= link_to "Cancel request and return to articles listing",articles_path %> ]
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="row">
      <div class="col-xs-8 col-xs-offset-2">
        <div class="panel panel-danger">
          <div class="panel-heading">
            <h2 class="panel-title">
              <%= pluralize(obj.errors.count, "error") %>
              prohibited this article from being saved:
            </h2>
            <div class="panel-body">
              <ul>
                <% obj.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>

    </div>
<% end %>